package de.lernspiel.common.code;

public enum LogType {
    LEVEL_SUCCESSFUL,
    LEVEL_UNSUCCESSFUL,
    SIMPLE_VARIABLE_DECLARATION,
    VARIABLE_DECLARATION_ASSIGNMENT,
    VARIABLE_VALUE_ASSIGNMENT,
    ERROR,
    PROGRAM_START,
    PROGRAM_END,
    IF_BRANCH_ENTERED,
    ELSE_IF_BRANCH_ENTERED,
    ELSE_BRANCH_ENTERED,
    NO_BRANCH_ENTERED;
}
